name: MonthBox
options:
  bundleIdPrefix: com.monthbox
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "8NKQAWBSBB"
    CODE_SIGN_STYLE: Automatic

targets:
  MonthBox:
    type: application
    platform: iOS
    sources:
      - MonthBox
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.monthbox.app
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_CFBundleDisplayName: MonthBox
        INFOPLIST_KEY_CFBundleIconName: AppIcon
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - target: MonthBoxWidgetExtension
    entitlements:
      path: MonthBox/MonthBox.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.application-groups:
          - group.com.monthbox.app

  MonthBoxWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: MonthBoxWidget
        excludes:
          - "Info.plist"
    info:
      path: MonthBoxWidget/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.monthbox.app.widget
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
    entitlements:
      path: MonthBoxWidget/MonthBoxWidgetExtension.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.application-groups:
          - group.com.monthbox.app

  MonthBoxTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - MonthBoxTests
    dependencies:
      - target: MonthBox
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.monthbox.app.tests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  MonthBox:
    build:
      targets:
        MonthBox: all
        MonthBoxWidgetExtension: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - MonthBoxTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
